apps/users/urls.py
from django.conf.urls import url
from . import views           # This line is new!
urlpatterns = [
  url(r'^$', views.index, name='index'), 
  url(r'^create$', views.create, name='create'),
  url(r'^login$', views.login, name='login'), 
	url(r'^logout$', views.logout, name='logout')
]

beltReviewer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('apps.users.urls', namespace='users')),
    url(r'^books/', include('apps.books.urls', namespace='books')),
]

apps/users/models.py
from __future__ import unicode_literals
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
import re
import bcrypt


EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
# Create your models here.
class UserManager(models.Manager):
  def validate_user(self, request):
    email = request.POST['email']
    password = request.POST['password']
    errors = []
    
    #Check first name
    if request.POST['firstName'] == '':         
      errors.append('First Name cannot be blank')
        
    if any(char.isdigit() for char in request.POST['firstName']) == True:              
      errors.append('First Name cannot have numbers')
    
    #Check last name
    if request.POST['lastName'] == '':             
      errors.append('Last Name cannot be blank')
        
    if any(char.isdigit() for char in request.POST['lastName']) == True:              
      errors.append('Last Name cannot have numbers')
 
    #Check email
    if request.POST['email'] == '':             
      errors.append('Email cannot be blank')
        
    if not EMAIL_REGEX.match(request.POST['email']):        
      errors.append('Invalid email address')
   
    #Check password
    if request.POST['password'] == '':      
      errors.append('Password cannot be blank')
        
    if len(request.POST['password']) < 8:              
      errors.append('Password must be greater than 8 characters')        
   
    #Check confirmation password
    if request.POST['confirmPassword'] == '':              
        errors.append('Please confirm password')
        
    if request.POST['confirmPassword'] != request.POST['password']:               
        errors.append('Passwords do not match')   

    try:
      self.get(email=email)
      errors.append('Email already in use.')
      return errors
    except:      
      return errors

  def reg_validation(self, request):
      # Refer back to the validation_error function
      errors = self.validate_user(request)
      # If there are any errors, return those errors instead of moving on
      if len(errors) > 0:
          return (False, errors)
      # If there are no errors, hash the password using Bcrypt, then add user to database
      pw_hash = bcrypt.hashpw(request.POST['password'].encode(), bcrypt.gensalt())
      user = self.create(first_name=request.POST['firstName'], last_name=request.POST['lastName'], email=request.POST['email'], password=pw_hash)
      return (True, user)

  def login_validation(self, request):
    # Check if user email and password are in database, and if they match    
    try:
        # user = self.get(email=request.POST['email'])
        # password = request.POST['password'].encode()      
        # if bcrypt.checkpw(password.encode(),  user.password.encode()):
        user = self.get(email=request.POST['email'])
        hashed = user.password        
        hashed = hashed.encode('utf-8')        
        password = request.POST['password']
        password = password.encode('utf-8')        
        if bcrypt.hashpw(password, hashed) == hashed:          
          return (True, user)
      # If neither exist, just return false automatically. If one of these returns false, return the same result to keep confidentiality
    except ObjectDoesNotExist:
      pass
    return (False, ["Email/password don't match"])

class User(models.Model):
  first_name = models.CharField(max_length=30)
  last_name = models.CharField(max_length=30)
  email = models.CharField(max_length = 60)
  password = models.CharField(max_length = 30) 
  created_at = models.DateTimeField(auto_now_add = True)
  updated_at = models.DateTimeField(auto_now = True)
  objects = UserManager()
  

apps/users/views.py
from django.shortcuts import render, redirect, reverse
from .models import User
from django.contrib import messages

def index(request):  
    if 'first_name' not in request.session:
        return render(request, 'users/index.html') 
    else:        
        return redirect('/books/home')       

def create(request):
    result = User.objects.reg_validation(request)
    if result[0] == False:
        for error in result[1]:
            messages.error(request, error)
        return redirect('users:index')  
    else:
        user = User.objects.get(email = request.POST['email'])
        request.session['first_name'] = user.first_name
        request.session['user_id'] = user.id
        return redirect('/books/home')        

def login(request):    
    result = User.objects.login_validation(request)
    if result[0] == False:
        for error in result[1]:
            messages.error(request, error)
        return redirect('users:index')
    else:
        user = User.objects.get(email = request.POST['email'])
        request.session['first_name'] = user.first_name
        request.session['email'] = user.last_name
        request.session['user_id'] = user.id
        return redirect('/books/home')
      
def logout(request):
    # request.session.pop('user')
    request.session.clear()
    return redirect('/users')

apps/users/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
   {% load staticfiles %}   
  <link rel="stylesheet" href="{% static '/users/css/style.css' %}">  
  <title>User Management</title>
</head>
<body>
  <h2>Welcome!</h2>      
  {% if messages %}
  
    <ul class="errors">
    <p><strong>Please fix errors:</strong></p>
      {% for message in messages %}
        <li>{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}
  <div class="container register">
  <h3>Register Users</h3>
  <form action="{% url 'users:create' %}" method="post">
    {% csrf_token %}
    <p><label>First Name:</label> <input type="text" name="firstName" ></p>
    <p><label>Last Name: </label><input type="text" name="lastName" ></p>
    <p><label>Email: </label><input type="text" name="email">  </p>  
    <p><label>Password:</label><input type="password" name="password"></p>
    <p><label>Confirm Password:</label> <input type="password" name="confirmPassword"></p>
    <p> <input type="submit" value="Register"></p>
  </form>
  </div>
 <div class="container">
  <h3>Login:</h3>
  <form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <p><label>Email:</label>
    <input type="text" name="email"> </p>
    <p><label>Password:</label>
    <input type="password" name="password"></p>
    <p><input type="submit" value="Login"></p>
  </form>
  </div>
  
  
</body>
</html>

apps/users/templates/users/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>User Management - Success Page</title>
</head>
<body>
    <div>

        <h1>Great Success!</h1>
        <p>You did it! You totally logged in, {{request.session.user.first_name}}.</p>
        <form action="/logout">
            <input type="submit" value='Log Out'>
        </form>
    </div>
</body>
</html>

apps/users/templates/users/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>User Management Success </title>
</head>
<body>
    <div>

        <h1>Great Success!</h1>
        <p>You did it! You totally logged in, {{request.session.user.first_name}}.</p>
        <form action="/login/logout" method="post">
            {% csrf_token %}
            <input type="submit" value='Log Out'>
        </form>
    </div>
</body>
</html>