apps/books/urls.py
from django.conf.urls import url
# from views import *
from . import views  
# from django.contrib import admin

urlpatterns = [
    url(r'^home$', views.home, name = "home"),
    url(r'^add_book/$', views.add_book, name="add_book"),
    url(r'^create_review/(?P<id>\d+)$', views.create_review, name="create_review"),
    url(r'^show/(?P<id>\d+)$', views.show, name="show"),
    url(r'^user/(?P<id>\d+)$', views.user, name="user"),
    url(r'^destroy/(?P<id>\d+)$', views.destroy, name="destroy"),
    # url(r'^admin/', admin.site.urls),
]

apps/users/urls.py
from django.conf.urls import url
from . import views           # This line is new!
urlpatterns = [
  url(r'^$', views.index, name='index'), 
  url(r'^create$', views.create, name='create'),
  url(r'^login$', views.login, name='login'), 
	url(r'^logout$', views.logout, name='logout')
]

beltReviewer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('apps.users.urls', namespace='users')),
    url(r'^books/', include('apps.books.urls', namespace='books')),
]

apps/books/models.py
from __future__ import unicode_literals
from django.db import models
from ..users.models import *

# Create your models here.
class Book(models.Model):
    book_title = models.CharField(max_length=45)
    author = models.CharField(max_length=45)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

class Review(models.Model):
    review = models.TextField(max_length=1000)
    rating = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at= models.DateTimeField(auto_now=True)
    user= models.ForeignKey(User, related_name="user_reviews")
    book= models.ForeignKey(Book, related_name="book_reviews")
  

apps/books/views.py
from django.shortcuts import render, redirect

from django.db.models import Count
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import *


# Create your views here.
def home(request):    
    if not 'first_name' in request.session:
        return redirect('users:index')        
    else:
        reviews = Review.objects.all().order_by('-id')[:3]
        books = Book.objects.all()
        context = {
            'reviews':reviews,
            'books':books
        }
        return render(request, 'books/home.html', context)

def add_book(request):
    if not 'first_name' in request.session:
        return redirect('users:index')
    else:
        if request.method == 'POST':
            author=''
            # if not Book.objects.filter(author=request.POST['author1']):
            #     messages.error(request, "Please select or add author")
            # if Book.objects.get(author=request.POST['author1']):
            #     author=request.POST['author1']           
            if len(request.POST['author1']) < 1 or request.POST['author1'] == '' or request.POST['author1'] == '0':
               
                if len(request.POST['author2'])<1:
                    
                    messages.error(request, "Please select or add author") 
                    return redirect('books:add_book')  
                    # return render(request, 'books/add_book.html')                          
                else:
                    author=request.POST['author2'] 
            else:
                author=request.POST['author1'] 
                # try:
                #     print("intryblock")
                #     Book.objects.filter(author=request.POST['author2'])
                #     messages.error(request, "This author exists in DB. Please select or add new")   
                #     return render(request, 'books/add_book.html', context)                                 
                # except:     
                #     author=request.POST['author1'] 

            # if len(request.POST['author2'])>1:
            #     author=request.POST['author2']

            if not Book.objects.filter(book_title=request.POST['book_title'], author=author):
                Book.objects.create(book_title=request.POST['book_title'], author=author)
                book = Book.objects.get(book_title=request.POST['book_title'], author=author)
                book.book_reviews.create(review=request.POST['review'], rating = request.POST['rating'], user_id=request.session['user_id'])
                storage = messages.get_messages(request)
                for _ in storage: 
                    pass

                if len(storage._loaded_messages) == 1: 
                    del storage._loaded_messages[0]
                # return redirect(reverse('books:show', kwargs={'id':book.id})) 
                return redirect('books:show', id=book.id)

                # -- This is not rite -- 
                # return redirect('books:show', args={'id':book.id})  
                # NoReverseMatch at /books/add_book/
                # Reverse for 'show' with keyword arguments '{'args': {'id': 19}}' not found. 
                # 1 pattern(s) tried: [u'books/show/(?P<id>\\d+)$']
                           
                # context  does not work with redirects only with render
                # context={
                #     'id': book.id
                # }
                # return redirect('/books/show/', context)
           

            else:                
                messages.error(request, "Book with that title/author already exists") 
                return redirect('books:add_book')  

        books=Book.objects.all()
        context={
            'books': books
        }
      
        return render(request, 'books/add_book.html', context)

def show(request, id):
    if not 'first_name' in request.session:
        return redirect('users:index')
    else:
        
        book = Book.objects.get(id=id)
        reviews = book.book_reviews.all()
        context = {
            'book': book,
            'reviews':reviews
        }
        return render(request, 'books/book_reviews.html', context)

def create_review(request, id):
    if not 'first_name' in request.session:
        return redirect('users:index')
    else:
        Review.objects.create(review=request.POST['new_review'], rating=request.POST['rating'], book_id=id, user_id=request.session['user_id'])
        # return redirect(reverse('books:show', kwargs={'id':id}))
        return redirect('books:show', id=id)
        # return redirect('books:show', kwargs={'id':id})

def destroy(request, id):
    if not 'first_name' in request.session:
        return redirect('users:index')
    else:
        Review.objects.get(id=id).delete()
        # return redirect(reverse('books:home'))
        return redirect('books:home')

def user(request, id):
    if not 'first_name' in request.session:
        return redirect('users:index')
    else:
        user = User.objects.get(id=id)
        reviews = user.user_reviews.all()
        total = len(reviews)
        context = {
            'user':user,
            'reviews':reviews,
            'total':total
        }
        return render(request, 'books/user_reviews.html', context)

apps/books/templates/books/add_book.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Add Book and Review</title>   
    <link rel="stylesheet" href="{% static 'books/css/books.css' %}">
  </head>
  <body>
    <div>        
      <ul class="nav">
        <li><h3>Welcome, {{request.session.first_name}}!</h3></li>
        <li id="nav"> <a href="{% url 'books:home' %}">Home</a></li>|
        <li><a href="{% url 'books:add_book' %}"> Add Book </a></li>|          
        <li><a href="{% url 'users:logout' %}">Logout</a></li>
      </ul>
    </div>    

    {% if messages %}
    <ul class="errors">
      {% for message in messages %}
        <li >{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}

    <div class="add-review">
      <h4>Add A New Book and Review</h4>
      <form  action="{% url 'books:add_book' %}" method="post">
        {% csrf_token %}
        <div>
          <label for="book_title" >Book Title</label>
          <div >
            <input type="text" name="book_title" class="form-control" placeholder="Book Title">
          </div>
        </div>

        <div>
          <label for="author" >Author</label>
          <div >
            <select class="form-control" name="author1">
              <option value="0">Choose From List</option>
            {% for book in books %}
              <option value="{{book.author}}">{{book.author}}</option>
            {% endfor %}
            </select>
            <input type="text" name="author2" class="form-control" placeholder="Add New Author">
          </div>
        </div>

        <div>
          <label for="review" >Review</label>
          <div>
            <textarea  name="review" rows="3" placeholder="Review"></textarea>
          </div>
        </div>

        <div >
          <label for="rating" >Rating</label>
          <div >
            <select  name="rating">
              <option value="*">*</option>
              <option value="**">**</option>
              <option value="***">***</option>
              <option value="****">****</option>
              <option value="*****">*****</option>
            </select>
          </div>
        </div>

        <div >
          <div>
            <button type="submit" >Add Book and Review</button>
          </div>
        </div>
      </form>
    </div>
  </div>
  </body>
</html>

apps/books/templates/books/book_reviews.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Book Reviews</title>    
    <link rel="stylesheet" href="{% static 'books/css/books.css' %}">
  </head>
  <body>
   <div>        
      <ul class="nav">
        <li><h3>Welcome, {{request.session.first_name}}!</h3></li>
        <li id="nav"> <a href="{% url 'books:home' %}">Home</a></li>|
        <li><a href="{% url 'books:add_book' %}"> Add Book </a></li>|          
        <li><a href="{% url 'users:logout' %}">Logout</a></li>
      </ul>
    </div>
      {% comment %} {% if messages %}
        {% for message in messages %}
          {{message}}
        {% endfor %}
      {% endif %} {% endcomment %}
      {% if messages %}
          <ul class="loginerrors">
            {% for message in messages %}
              <li {% if message.tags %}
                class="{{ message.tags }}"
              {% endif %}>{{ message }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      <div >
        <h3>Book: {{book.book_title}} <span class="glyphicon glyphicon-book"></span></h2>
        <p>Author: {{book.author}} </p>
      </div>
      <div class="allReviews">
        {% for review in reviews %}
        <div class="review">
          <h4><strong>Rating: </strong>{{review.rating}}</h4>
          <h4><strong><a href="{% url 'books:user' id=review.user.id %}">{{review.user.first_name}}</a> says: </strong>{{review.review}}</h4>
          <h5>{{review.created_at}}</h5>
          
          {% if request.session.user_id == review.user.id %}
            <h4><a  href="{% url 'books:destroy' id=review.id %}" role="button">
              Delete 
            </a></h4>
          {% endif %}
        </div>
        {% endfor %}
      </div>
      <div class="addreviewSide">
        <div class="add-review ">
          <h3>Add Review</h3>
          <form class="form-horizontal" action="{% url 'books:create_review' id=book.id %}" method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="new_review" class="col-sm-1 control-label">Review</label>
              <div class="col-sm-6">
                <textarea class="form-control" name="new_review" rows="3"></textarea>
              </div>
            </div>

            <div class="form-group">
              <label for="rating" class="col-sm-1 control-label">Rating</label>
              <div class="col-sm-6">
                <select class="form-control" name="rating">
                  <option value="*">*</option>
                  <option value="**">**</option>
                  <option value="***">***</option>
                  <option value="****">****</option>
                  <option value="*****">*****</option>
                </select>
              </div>
            </div>

            <div class="form-group">
              <div class="col-sm-offset-1 col-sm-6">
                <button type="submit" class="btn btn-info">Add Review</button>
              </div>
            </div>
          </form>
      </div>
      </div>
    </div>
  </body>
</html>

apps/books/templates/books/home.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Home Page</title>   
    <link rel="stylesheet" href="{% static 'books/css/books.css' %}">
  </head>
  <body>
      <div>        
        <ul class="nav">
          <li><h3>Welcome, {{request.session.first_name}}!</h3></li>
          <li id="nav"> <a href="{% url 'books:home' %}">Home</a></li>|
          <li><a href="{% url 'books:add_book' %}"> Add Book </a></li>|          
          <li><a href="{% url 'users:logout' %}">Logout</a></li>
        </ul>
      </div>
        
      {% if reviews %}
      <div class="allReviews">
        <h3>Recent Book Reviews </h3>        
        {% for review in reviews %}
          <div class="review">
            <h4><strong><a href="{% url 'books:show' id=review.book.id %}">{{review.book.book_title}}</strong></a></h4>
            <h4><strong>Rating: {{review.rating}}</strong></h4>
            <h4>{{review.user.first_name}} says: {{review.review}}</h4>
            <em><h5>{{review.created_at}}</h5></em>
          </div>
        {% endfor %}
      </div>
      
      <div class="review other">
        <h3>Other Books with Reviews </h3>
          {% for book in books %}
          <h4><a href="{% url 'books:show' id=book.id %}">{{book.book_title}}</a></h4>
          {% endfor %}
      </div>

      {% else %}

      <div >
        <h1>Hello, {{request.session.first_name}}!</h1>
        <p>There are currently no reviews! Please add one! </p>
      </div>

      {% endif %}
    
  </body>
</html>

apps/books/templates/books/user_reviews.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>User Reviews</title>   
    <link rel="stylesheet" href="{% static 'books/css/books.css' %}">
  </head>
  <body>
    <div>        
      <ul class="nav">
        <li><h3>Welcome, {{request.session.first_name}}!</h3></li>
        <li id="nav"> <a href="{% url 'books:home' %}">Home</a></li>|
        <li><a href="{% url 'books:add_book' %}"> Add Book </a></li>|          
        <li><a href="{% url 'users:logout' %}">Logout</a></li>
      </ul>
    </div>
      <div class=>
        <h3>Name: {{user.first_name}} {{user.last_name}}</h3>
        <p>Email: {{user.email}}</p>
        <p>Total Reviews: {{total}}</p>
        <p><strong>Posted Reviews on the following books:</strong></p>
        <ul class="userreviewes">
          {% for review in reviews %}
            <h4><li ><a href="{% url 'books:show' id=review.book.id %}">{{review.book.book_title}}</a></li></h4>
          {% endfor %}
        </ul>
      </div>
    </div>
  </body>
</html>